### ISSUE TITLE
Make default grid behavior for `FourierRZCurve` consistent with rest of objects that have `NFP` attibute

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#1118]
>Right but I mean now it is inconsistent behavior for NFP objects, where any other object with NFP as an attribute will compute on a grid from 0 -> 2pi/NFP except `FourierRZCoil/Curve`
>This is fine but I will make an issue for this as I don't like the inconsistency

_Originally posted by @dpanici in https://github.com/PlasmaControl/DESC/pull/1099#discussion_r1670879252_

**Comment by ddudt** [comment]
We should discuss what we mean by consistent. After #1099 the `FourierRZCurve` default grid is now consistent with all the other coils, since it uses `NFP=1` to include points along the entire length of the coil. You are saying you would prefer it to be inconsistent with the other coils and instead consistent with all other objects that have NFP>1 to only have grid points in a single field period. It's not clear to me which is better in general for computing quantities along a curve. 

If we revert the changes from #1099 we need to edit the default grid in both `_CoilObjective.build` and `Curve.compute`, since those only pertain to curve geometry. `Coil.compute_magnetic_field` should always use `NFP=1` we think.

**Comment by dpanici** [comment]
make all curves have NFP=1 (use same N increase as was used in #1099 )
