### ISSUE TITLE
Timing Benchmarks

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#120]
Over the past few months our test suite has gotten a lot slower. In many ways this is expected, as we add more tests to comprehensively test more of the code, but it also makes it harder to tell when changes are actually slowing the code down. It would be good to start including systematic timing benchmarks as part of our regular test suite.

Pytest has a plugin to do something like that: https://pytest-benchmark.readthedocs.io/en/latest/index.html
And there's a Github Action to do it as part of our regular CI stuff and even make a spiffy webpage with the results: https://github.com/rhysd/github-action-benchmark

I don't think it would be too hard to set up, we could start with benchmarking the basic equilibrium solves for the DSHAPE and SOLOVEV solutions, plus hopefully a simple stellarator case. We could also include micro benchmarks for smaller parts of the code like computing transforms, compiling jacobians, etc.

On a related note, we should also try to reduce the overall testing time where possible (using lower resolution, smaller arrays, etc), we're coming up on 20-30 mins depending on hardware.

**Comment by dpanici** [comment]
Pushed a benchmark branch, but needs to be more automated. Also finding an issue with trying to benchmark building transforms, it seems JAX must cache some of the function evaluations as the first time building the object takes a long time, then attempting to re-make the object and re-build it (by re-make I mean executing `transf=Transform(grid,basis,build=False)` then `transf.build()` again) results in a much much faster build time. @f0uriest is there a way to tell JAX to not do this caching for benchmarking purposes? Or is it valuable information to let JAX 'warmup' with an iteration? I would think not since the first build is always what takes the longest

**Comment by dpanici** [comment]
To use the benchmarking action, add the `run_benchmarks` label to a PR. This will trigger the benchmarks action, which compares the performance of the latest commit on that PR to the performance of the master branch, and posts the comparison as a comment on the PR.

If the PR already has the `run_benchmarks` label and you want to run them again, remove the label (by clicking the `run_benchmarks` label and then clicking out of the label selection box), then re-add the `run_benchmarks` label.

**Comment by f0uriest** [comment]
Does it test the master and PR with the same dependencies, or does it redo ``pip install -r requirements.txt`` before each one? If we update requirements in a PR it would be good to have it use the correct ones.
To be safe we could do ``pip install -r requirements.txt`` before each, and ``pip uninstall -r requirements.txt`` after
