### ISSUE TITLE
Normalization of plot_2d()

### ISSUE THREAD

**Issue by mohawk811** [PlasmaControl/DESC#1371]
`plot_2d(eq_out,'J',log=False, norm_F=True)`

Is there a way to normalize to grad B and not grad B^2?

<img width="338" alt="Screenshot 2024-11-15 at 12 41 29 PM" src="https://github.com/user-attachments/assets/441bb467-430f-4037-94a5-8731e66471e3">

**Comment by YigitElma** [comment]
You can use `norm_name` argument to adjust the normalization. Something like,

```python
plot_2d(eq,'J',log=False, norm_F=True, norm_name="grad(|B|)")
```
But this might not give proper results, since (as far as I know) we don't have a compute function for `"|grad(|B|)|"` or something similar.

**Comment by mohawk811** [comment]
Is there a way to still have the 1/2mu0 ?

**Comment by YigitElma** [comment]
If you want to use `plot_2d` function, I don't think you can because we don't have a compute function for $|\nabla B|/2\mu_0$. If you want you can write your own compute function following [this page](https://desc-docs.readthedocs.io/en/latest/adding_compute_funs.html). But probably the easiest way is to compute $|\nabla B|$ and then divide it by $\mu_0$ and plot it using `plt.contourf` instead of `plot_2d`.

**Comment by dpanici** [comment]
Yea I recommend just computing the stuff yourself and plotting yourself if you need a custom normalization. You can use the `return_data` flag of `plot_2d` if you want to use that to get the R,Z and |F| instead of doing it yourself, and you can look at the source for `plot_2d` if you need to check how the reshaping needs to be to plot the data.

**Comment by YigitElma** [comment]
I believe this issue is resolved. If you should either,

- write your own compute function
- use existing compute functions to calculate your normalization, and use `plt.contourf`

Feel free to re-open, if you think those won't solve your problem.
