### ISSUE TITLE
"vacuum" objective

### ISSUE THREAD

**Issue by Mandelbr0t** [PlasmaControl/DESC#1408]
Reading through desc issues regarding vacuum equilibria, I came across the "vacuum" objective multiple times (J^rho=J^theta=J^zeta=0). 
But it seems like it isn't implemented any more. What is the reason for omitting it in the current desc versions?

**Comment by ddudt** [comment]
The [CurrentDensity](https://github.com/PlasmaControl/DESC/blob/master/desc/objectives/_equilibrium.py#L737) objective still exists, which minimizes the plasma current and can be used for solving vacuum equilibria. We used to have a shortcut for doing this as `eq.solve(objective="vacuum")`, which you may have seen in old posts. We removed this because we were afraid users would use it incorrectly (it is only valid if the equilibrium has vacuum profiles of no pressure and no current), and typically the `objective="force"` option works just as well for vacuum cases. The previous behavior can still be reproduced by passing the `CurrentDensity` objective explicityly.
