### ISSUE TITLE
Bug in Fourier boundary fit when sin(theta) mode for Z is nonzero

### ISSUE THREAD

**Issue by unalmis** [PlasmaControl/DESC#1435]
When the $m=-1, n=0$ mode for $Z(\theta, \zeta)$ on boundary is nonzero, it seems we compute the position $R(\theta, \zeta)$ of the boundary  incorrectly. Please see bc768b45d3d3db80e00f9331f92de60aef3526a7 for more info. The command ``pytest -p no:warnings -k test_laplace_dommaschk`` will be useful.

**Comment by unalmis** [comment]
Is this expected from flipping the orientation @f0uriest ?

**Comment by dpanici** [comment]
I don't completely understand the issue from your linked test, but if you compute `theta` for one of the representations as the negative of what you give for the other, do the results match? That would indicate the difference is in the orientation flip

If the[ input boundary ](https://github.com/PlasmaControl/DESC/blob/d8d3784595a6600335497fce531f82fe2b69ae79/desc/geometry/surface.py#L140)to an Equilibrium (or surface) has the [poloidal angle increasing](https://github.com/PlasmaControl/DESC/blob/d8d3784595a6600335497fce531f82fe2b69ae79/desc/geometry/core.py#L400) in the CCW direction instead of CW, we [flip the orientation](https://github.com/PlasmaControl/DESC/blob/d8d3784595a6600335497fce531f82fe2b69ae79/desc/geometry/core.py#L424) by reversing the sign of every mode with m<0, so in this case it would change the sign of the Z(m=-1, n=0) mode, yes

**Comment by unalmis** [comment]
Yes if I negate $\theta$ when DESC flips the orientation, I recover the expected result. Is this sufficient in general, or does the staring point also change location?

**Comment by unalmis** [comment]
Ok I thought this was done internally, so that the user can keep using the parameterization they provided and desc internally flips the sign.

**Comment by dpanici** [comment]
> Yes if I negate θ when DESC flips the orientation, I recover the expected result. Is this sufficient in general, or does the staring point also change location?

we never change the starting point, we only will flip mode signs to reverse the poloidal direction to be CW
