### ISSUE TITLE
Question of Adding Zonal Flow Residue Level as a Scalar Objective Function

### ISSUE THREAD

**Issue by handi-h** [PlasmaControl/DESC#1486]
Hi guys,

Apologies for reaching out right before the holidays—please feel free to respond at your convenience.

I’m trying to add a new objective function for my optimization, specifically the zonal flow residue level, which is a scalar calculated from the flux surface integral (refer to Eqs. 2.3, 2.11, and 2.21 in [this paper](https://sun.ps.uci.edu/zlin/bib/zhuhx24.pdf)). While the computation provides the correct f value, the optimization does not progress as expected. I’ve attached the Jupyter notebook I used for testing.
[zonal_rasidue.ipynb.zip](https://github.com/user-attachments/files/18219645/zonal_rasidue.ipynb.zip)

I also noticed that many flux surface integral objective functions output a vector rather than a scalar, and I’m unclear where the flux surface integral operation is performed. For the formula of this objective function, I need to output a scalar because the integral appears in the denominator rather than the numerator.

Thank you, and happy holidays!

Best,
Handi

**Comment by f0uriest** [comment]
Haven't gone though the paper or notebook in detail but a few comments:
- Generally the compute functions for flux surface averages return arrays corresponding to the full grid, but with every point on the same surface having the same value. This is so that they correctly broadcast against other data on the same grid. The grid class methods `compress` (keeps just the unique values for each flux surface) and `expand` (duplicates unique values to broadcast against other qtys on the same grid) allow you to convert between different representations. Generally for objectives that output surface averaged qtys we do `compress` in the objective so that it only returns the unique values.
- There are utility functions in `desc.integrals` for computing surface averages that I'd recommend over rolling your own. There are some subtleties with symmetric grids and grids with multple surfaces that it can be tricky to get right (though unclear if that could be causing your issues, it looks fine at first glance)
- As for why the objective is returning zero, its kind of subtle but basically you need to change `_coordinates` for the zonal flow objective to `r`, not `rtz` because its a surface average qty, so doesn't depend on theta/zeta (internally we use this to set some quadrature weights so that the sum of squares of the objective approximates the volume integral, and those weights were being set incorrectly bc the grid has a bunch of points but only 1 value was being returned)

**Comment by handi-h** [comment]
Thank you so much for your explanation. Your insights help a lot!

Best,
Handi
