### ISSUE TITLE
Add nested flux surfaces check to optimizer callback

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#180]
When performing the force minimization at a step where the surfaces end up unnested, sometimes the minimization can take a long time, only for the end result to be non-nested surfaces. Adding a call to the `is_nested` function to the callback would let us exit the optimization early as soon as surfaces become nested

will double check how long this nested check takes, if it would add a lot of overhead to the minimization we could have it only run every certain number of function evals or every 5 mins or something like that

**Comment by f0uriest** [comment]
I had something like this a while back, but I found that it did end up taking a lot longer, relative to the optimization step. Another thing is that in some cases, its ok if it becomes un-nested for a single iteration or something, it can still recover (also because the ``is_nested`` check isn't perfect, and sometimes says things aren't nested when they really are, due to the way it discretizes and evaluates the topology)
