### ISSUE TITLE
Specify initial guess / restarting

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#36]
We should have an easy way to either specify an initial guess, or to restart from a previous run at a certain point.

**Comment by patil3** [comment]
I was wondering if this functionality currently under development. It would be really helpful if it's possible to just use a saved .h5 file or a .nc file.
I also saw the following issue when trying to use a vmec file as a guess as noted in the documentation:
With `desc -o dshape --vmec wout_DSHAPE.nc -vv DSHAPE`, I get an error (see disp.txt).
[disp.txt](https://github.com/PlasmaControl/DESC/files/6713610/disp.txt)

Something similar to this for the .h5 files generated by desc would be really helpful.

**Comment by patil3** [comment]
copy_coeffs seems useful. I will check it out. I suppose I could look at the way vmec output is used as a guess and try to write something similar for desc outputs.
Essentially, I would want the code to use the magnetic field (R_lmn, Z_lmn) calculated and saved in a previous run as the initial guess, instead of the surfaces obtained by scaling the boundary surface. The resolution and the profiles used should still be the ones from the input file. The way I would want to specify this guess is similar to the --vmec flag: `desc -o output.h5 --guess guess_solution.h5 -vv input_file`

**Comment by f0uriest** [comment]
@patil3 I recently updated the init method for the Equilibrium class and how initial guesses get created to allow for more functionality, and updated the command line interface to be more in line with what you suggested. Feel free to check out the equil_constructor branch in #121 and let me know if you have any thoughts / suggestions
