### ISSUE TITLE
Examples that need tweaking as default input file is not robust

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#412]
based on running examples on CPU on Stellar, bolded ones I should change:

 - [ ]  **ATF**: surfaces no longer nested after last step, time: 3.56 min
 - [ ]  **ARIES-CS**: Seems to run ok, long though, time: 3.23 hours
 - [ ]  **CFQS**: surfaces no longer nested after 4th step, time: 18 min
 - DSHAPE: runs fine, time: 40 sec
 - DSHAPE_current: runs fine, time: 50 sec
 - ESTELL: runs fine, time: 13 min
 - HELIOTRON: runs fine, time: 10.4 min
 - [ ]  **HSX**: immediately goes unnested, due to only being 1 tep and probably the bdry is too strongly shaped. Also uses scipy-trf instead of lsq-exact
 - NCSX: runs fine, time: 41 min
 - QAS: runs fine, time:  8.5 min
 - SIMSOPT_QA: runs fine, time: 2.3 min
 - W7-X: on step 7, the radial spectral resolution is higher than the radial grid resolution, but this is because I switched it to ANSI... so maybe not a good representation of this example. ends up going unnested at last step but will re-run with current defaults
 - WISTELL-A: seems to run fine, time: 20.1 min

**Comment by f0uriest** [comment]
I tried a naive truncation of HSX (just cutting out high order modes) but the resulting boundary has some tiny wiggles that look weird and it gives a different answer from VMEC (which I guess is expected since VMEC is using the full res?). We should re-run VMEC on the truncated one and see if they match, and if they do use that as our example case (replacing both HSX ones in the VMEC folder and the one in the DESC folder)
