### ISSUE TITLE
eq.compute("p") returns kinetic quantities even if equilibrium has no kinetic profiles set

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#442]
Currently, we have behavior like this when we compute pressure
![image](https://user-images.githubusercontent.com/37969854/222001180-29c143ef-af74-42a5-b142-a14786acdbbf.png)

where the keys returned include the kinetic quantities, even though this equilibrium only has pressure assigned to it. I would think we don't want to return these kinetic quantities unless the equilibrium has them assigned?

**Comment by ddudt** [comment]
I think this happens because `eq.compute` always returns all of the intermediate quantities that were needed to compute the final quantity you requested. Pressure is defined to be "dependent on" the kinetic quantities, even though they aren't actually required for this case were the pressure profile was given. So I think this behavior makes sense and those kinetic quantities it returns should be `None`.

**Comment by f0uriest** [comment]
Yes, @ddudt is correct. Pressure depends on the kinetic profiles because dealing with optional dependencies was really messy. If kinetic profiles aren't assigned it should return Nan for those

**Comment by dpanici** [comment]
- [ ] Make sure notebooks say the correct behavior (currently a disconnect btwn what happens and what the text says should happen)

**Comment by f0uriest** [comment]
I think it's correct as is, the text is
> Notice that the returned dictionary for iota has more than just iota as a key. Generally, `eq.compute` will return the desired quantity along with each of its dependencies needed to calculate that quantity. Don't rely on this, to ensure that you get all the quantities you need, it is better to pass in explicitly each quantity, for example you want both `p` and `p_r`, you must call `eq.compute(["p","p_r"])`.
