### ISSUE TITLE
Plot vartheta lines look off on latest master

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#477]
on current master
![image](https://user-images.githubusercontent.com/37969854/229616955-c94bfe16-108e-4530-892e-d5d02aef7462.png)

before current master (`git checkout b73756b`)

![image](https://user-images.githubusercontent.com/37969854/229617394-4152d951-54bf-4201-8807-694b522b41ac.png)

probably related to the symmetry stuff?

**Comment by unalmis** [comment]
A better example of the issue is with Heliotron. A common thing is that the cross section at zeta = 0 is not affected. Also, after solving an input on the latest master, if I return to your `b73756b` to run the plot command I recover the good looking vartheta lines. This makes me think its some type of plotting issue.
