### ISSUE TITLE
Unequal number of field periods

### ISSUE THREAD

**Issue by unalmis** [PlasmaControl/DESC#594]
Is this warning expected from the following code?
`DESC/desc/transform.py:65: UserWarning: Unequal number of field periods for grid 5.0 and basis 1.`

```python
from desc.backend import jnp
from desc.examples import get
from desc.grid import LinearGrid

eq = get("W7-X")
rho = jnp.linspace(0, 1, 20)
lg = LinearGrid(rho=rho, L=5, N=5, sym=eq.sym, NFP=eq.NFP)
pp = eq.iota.compute(grid=lg)
```

related to #478

**Comment by dpanici** [comment]
Which line makes the warning? The last or second to last?

**Comment by f0uriest** [comment]
I think the purpose of the warning was to catch the opposite case (where the basis has NFP>1 and the grid has NFP==1) because in those cases averages compute with that grid will be wrong. But in this case it's kind of overkill because the basis has N==0 so any NFP is fine. We should add `and basis.N != 0` to the conditional in `desc.transform.py`

**Comment by ddudt** [comment]
There are also many cases where this warning is thrown when we compute quantities on the full torus $\zeta\in[0,2\pi)$ using `NFP=1`, but the basis has `NFP>1`. This comes up often in plotting routines, etc. and is annoying, but I can't think of a good check because it depends on the application.

**Comment by f0uriest** [comment]
@ddudt any thoughts for a better fix?
