### ISSUE TITLE
Plot_Surfaces is very slow when plotting vartheta contours

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#608]
I've noticed that plot_surfaces is noticeably slower than it was in the mid-past (a few months ago), when the vartheta contours are plotted. Wonder if a change to how those are calculated is the cause (like in map coords or something)

**Comment by f0uriest** [comment]
Yeah I've noticed that as well. `map_coordinates` is more general, but that comes at the expense of speed if you only need root finding in theta. I was thinking of putting in a shortcut so that if you call `map_coordinates` looking for `rho, vartheta, zeta` it calls `compute_theta_coords` instead. Might be a bit trickier though with the generalized toroidal angle, since its then a 2d problem instead of 1d
