### ISSUE TITLE
Contravariant metric and basis vectores for Surfaces

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#645]
Surface currently cannot compute these, and need to be either added or the parametrizations updated

 - [x] R
 - [x] Z
 - [x] phi
 - any contravariant metric elements (these would likely need to be calculated with inverting the metric tensor)
 - contravariant basis vectors (is this possible for the surface? can these be backed out from the metric elements?)

**Comment by f0uriest** [comment]
- for R, phi, Z we could add dummy functions that just slice that part of `x`?
- g_ii derivatives should work, they're in `compute/_metric.py` and already have `Surface` as a parameterization
- for the metric tensor stuff it might be a good idea to add a compute function for the full metric tensor as a 3x3 matrix (or 2x2 matrix for surfaces) rather than always having to build it from the elements
- i think it is possible to back out the contravariant basis vectors if we have the contravariant metric tensor elements

$e_i \cdot e^i = 1$
$e_j \cdot e^i = 0$
$e^i \cdot e^i = g^{ii}$

3 equations in 3 unknowns (components of $e^i$

**Comment by dpanici** [comment]
Ah might have been my branch was not fully up to date, but I thought when I checked I did not find the derivs I needed. But yea these are good ideas, I will make a PR for this early next week

**Comment by dpanici** [comment]
Idea: assign radial derivs by scaling surface down to centroid, then compute normally (with caveat that rho derivs are meaningless)

**Comment by dpanici** [comment]
@dpanici  revisit this

**Comment by dpanici** [comment]
Only partially though, contravariant basis and metric elements are not defined for a surface still (though maybe that is just because they are ill-defined)
