### ISSUE TITLE
Increasing Radial Resolution Past certain amount with asym can cause Linear Constraint Factor to fail

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#730]
SK found an axisymmetric, asymmetric case where once he increased the L=M spectral basis resolution past about 40, the linear constraint factorization threw an error, complaining that it could not satisfy the boundaryR self consistency

[input_D3D.txt](https://github.com/PlasmaControl/DESC/files/13183556/input_D3D.txt)

**Comment by f0uriest** [comment]
That input file runs fine for me, but it only seems to go up to M=20

When I try M=40 on a circular tokamak I do get the error, but I think it might just be due to the limits of double precision. Here are the singular values of the constraint A matrix:

![image](https://github.com/PlasmaControl/DESC/assets/22567458/9191b70b-27f4-4c66-8d8c-1094cbc4e74e)

**Comment by dpanici** [comment]
Ok yea I figured that was the problem but just wanted to make an issue for it. I will close it then for now

**Comment by dpanici** [comment]
I think this is may have been related to #1369 as well (at least, I have found that in this case where I had the inconsistent constraints warning before, I no longer get it with the change of the LambdaGauge constraint)
