### ISSUE TITLE
Bug when printing start and end of solver values for optimization with verbose = 3

### ISSUE THREAD

**Issue by pkim1818** [PlasmaControl/DESC#748]
When running an optimization with verbose = 3, it's supposed to print out the start and end of solver values. However, it only prints out the end of solver values.
![image](https://github.com/PlasmaControl/DESC/assets/68658570/b6f48f14-aea7-4946-8dbe-e0ba4b4f0e84)

**Comment by YigitElma** [comment]
Can this just be a consequence of a very low number of iterations? For higher number of iterations, do you still have that problem?

**Comment by pkim1818** [comment]
I don't think it's a number of iterations issue. You can also see that it's only printing the final sum of squares.
<img width="764" alt="image" src="https://github.com/PlasmaControl/DESC/assets/68658570/11f768ab-6217-40c2-98d3-79a28e827469">

**Comment by f0uriest** [comment]
I think it's an issue specific to the proximal projection wrapper, since that modifies the equilibrium as it goes rather than updating everything at the end. I'm not sure of the best fix, since we want to make sure that we keep track of the correct equilibrium and that the objectives bound to that equilibrium get handled correctly.

**Comment by pkim1818** [comment]
I only started seeing this problem when I updated my branch a couple days ago (I had previously merged master into my branch a couple weeks prior). I can try to track which commit broke it sometime this week...

**Comment by pkim1818** [comment]
One fix I pushed is copying the initial state of things. Not sure if this is the best fix though. [https://github.com/PlasmaControl/DESC/blob/pk/verbose_fix/desc/optimize/optimizer.py#L149C6-L149C6](url)

**Comment by YigitElma** [comment]
I couldn't find any better way either. Btw, when you try to solve ProximalProjection by non "proximal-" method, there is a warning that it will use "proximal-method", but later it says Using method: "method without proximal". We can also fix it under this issue. Maybe return an additional string with _maybe_wrap_nonlinear_constraints() function and print it instead of self.method
