### ISSUE TITLE
Calling eq.axis.compute(names=["x"]) for NFP=1 returns "x" defined on multiple toroidal angles

### ISSUE THREAD

**Issue by Mandelbr0t** [PlasmaControl/DESC#974]
This is due to https://github.com/PlasmaControl/DESC/blob/master/desc/geometry/core.py#L109
where `N = self.N * 2 + 5 `

I'd expect "x" to be defined on phi==0. Is there a deeper reason for this behaviour?
If not, a quick fix would be `N=1 if NFP==1 else self.N*2+5`, which could be my first PR here.

**Comment by f0uriest** [comment]
I think this is expected. Even with a single field period there can be toroidal variation in the position, so `x` is generally not a constant.

**Comment by Mandelbr0t** [comment]
Makes sense, more specific I'm looking at an axisymmetric equilibrium here - the DSHAPE example.

**Comment by f0uriest** [comment]
In that case `x` is constant in cylindrical coordinates, though not in cartesian. And we usually set the default grid so that integral quantities (like length) are computed correctly, which requires several points along the curve. We could possible add special case logic depending on `curve.N` but I think it's probably more hassle than it's worth.
